# Generated by Django 5.0.2 on 2024-03-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('yearly_salary', models.FloatField()),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=10)),
                ('quote_type', models.CharField(choices=[('offer-one', 'Package Type One - $250'), ('offer-two', 'Package Type Two - $500'), ('offer-three', 'Package Type Three - $1000')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('client_name', 'client_email')},
            },
        ),
    ]
