# Generated by Django 5.0.2 on 2024-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Query Database',
            },
        ),
        migrations.CreateModel(
            name='VerifyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
