# Generated by Django 5.0.2 on 2024-03-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProj', '0002_querydatabase_verifyquote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifyquote',
            options={'verbose_name': 'Verify Quote'},
        ),
        migrations.AddField(
            model_name='verifyquote',
            name='admin_notif_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifyquote',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifyquote',
            name='quote',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='FinalProj.quoteform'),
        ),
    ]
