# Generated by Django 5.0.2 on 2024-03-10 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProj', '0003_alter_verifyquote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteform',
            name='yearly_salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
